"""Instruction-level routing before planner."""

from agent.routing.instruction_router import RouterDecision, route_instruction
from agent.routing.intent import (
    DEFERRED_PRIMARY_INTENTS,
    INTENT_AMBIGUOUS,
    INTENT_COMPOUND,
    INTENT_DOC,
    INTENT_EDIT,
    INTENT_EXPLAIN,
    INTENT_INFRA,
    INTENT_SEARCH,
    INTENT_VALIDATE,
    PLAN_SHAPE_DECOMPOSE_THEN_ROUTE,
    PLAN_SHAPE_DEFER_TO_PLANNER,
    PLAN_SHAPE_TWO_PHASE_DOCS_CODE,
    PLANNER_HANDOFF_CONFIDENCE_BELOW,
    PLANNER_HANDOFF_ROUTER_DISABLED,
    PLANNER_HANDOFF_UNCLEAR_INTENT,
    PLAN_SHAPE_DOCS_SEED_LANE,
    PLAN_SHAPE_PLANNER_MULTI_STEP,
    PLAN_SHAPE_SINGLE_STEP_EXPLAIN,
    PLAN_SHAPE_SINGLE_STEP_INFRA,
    PLAN_SHAPE_SINGLE_STEP_SEARCH,
    PLAN_SHAPE_SINGLE_STEP_VALIDATE,
    PRODUCTION_EMITTABLE_PRIMARY_INTENTS,
    RoutedIntent,
    default_plan_shape,
    is_production_emittable_primary,
    routed_intent_from_dict,
    routed_intent_from_router_decision,
)
from agent.routing.router_registry import get_router, get_router_raw, list_routers
from agent.routing.simple_router import route_intent_simple
from agent.routing.production_routing import route_production_instruction
from agent.routing.docs_intent import (
    DOCS_DISCOVERY_VERBS,
    DOCS_INTENT_TOKENS,
    is_docs_artifact_intent,
    is_two_phase_docs_code_intent,
)

__all__ = [
    "RouterDecision",
    "route_instruction",
    "get_router",
    "get_router_raw",
    "list_routers",
    "RoutedIntent",
    "route_intent_simple",
    "routed_intent_from_dict",
    "routed_intent_from_router_decision",
    "default_plan_shape",
    "DEFERRED_PRIMARY_INTENTS",
    "is_production_emittable_primary",
    "PRODUCTION_EMITTABLE_PRIMARY_INTENTS",
    "INTENT_SEARCH",
    "INTENT_DOC",
    "INTENT_EXPLAIN",
    "INTENT_EDIT",
    "INTENT_VALIDATE",
    "INTENT_INFRA",
    "INTENT_COMPOUND",
    "INTENT_AMBIGUOUS",
    "PLAN_SHAPE_SINGLE_STEP_SEARCH",
    "PLAN_SHAPE_DOCS_SEED_LANE",
    "PLAN_SHAPE_SINGLE_STEP_EXPLAIN",
    "PLAN_SHAPE_PLANNER_MULTI_STEP",
    "PLAN_SHAPE_SINGLE_STEP_VALIDATE",
    "PLAN_SHAPE_SINGLE_STEP_INFRA",
    "PLAN_SHAPE_DECOMPOSE_THEN_ROUTE",
    "PLAN_SHAPE_DEFER_TO_PLANNER",
    "PLAN_SHAPE_TWO_PHASE_DOCS_CODE",
    "PLANNER_HANDOFF_CONFIDENCE_BELOW",
    "PLANNER_HANDOFF_ROUTER_DISABLED",
    "PLANNER_HANDOFF_UNCLEAR_INTENT",
    "route_production_instruction",
    "is_docs_artifact_intent",
    "is_two_phase_docs_code_intent",
    "DOCS_INTENT_TOKENS",
    "DOCS_DISCOVERY_VERBS",
]
