"""Stable task_name strings for models_config.json (task_models + task_params).

Must match keys used in call_reasoning_model(..., task_name=...) for exploration LLM calls.
"""

EXPLORATION_TASK_V2 = "EXPLORATION_V2"
EXPLORATION_TASK_QUERY_INTENT = "EXPLORATION_QUERY_INTENT"
EXPLORATION_TASK_SCOPER = "EXPLORATION_SCOPER"
EXPLORATION_TASK_SELECTOR = "EXPLORATION_SELECTOR"
EXPLORATION_TASK_SELECTOR_SINGLE = "EXPLORATION_SELECTOR_SINGLE"
EXPLORATION_TASK_SELECTOR_BATCH = "EXPLORATION_SELECTOR_BATCH"
EXPLORATION_TASK_ANALYZER = "EXPLORATION_ANALYZER"

EXPLORATION_LLM_STAGE_TASKS = (
    EXPLORATION_TASK_QUERY_INTENT,
    EXPLORATION_TASK_SCOPER,
    EXPLORATION_TASK_SELECTOR_SINGLE,
    EXPLORATION_TASK_SELECTOR_BATCH,
    EXPLORATION_TASK_ANALYZER,
)
